---
id: devlove-2012
base_name: after-reading-readable-code
tags:
- rabbit
- readablecode
- devlove
- devlove2012
presentation_date: 2012/12/16
version: 2012.12.16.2
licenses:
- CC BY-SA 3.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author:
  markup_language: :rd
  name: 須藤功平
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
